spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/sid?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    database: mysql
    database-platform: org.hibernate.dialect.MariaDBDialect
    generate-ddl: true
#    defer-datasource-initialization: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+9
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: "clearrworld@gmail.com"
    password: xxxx
    properties:
      mail.smtp.debug: true
      mail.smtp.connectiontimeout: 1000 #1초
      mail.starttls.enable: true
      mail.smtp.auth: true
#  sql:
#    init:
#      mode: always

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

auth:
  oauth:
    kakao:
      api: xxxxx
      redirect-url: https://dev.si-d.site/oauth

jwt:
  expiration: 30
  secretKey: my_token_secret

cloud:
  aws:
    s3:
      bucket: sejeong-file
    stack.auto: false
    region:
      static: ap-northeast-2
    credentials:
      access-key: xxxxx
      secret-key: xxxxx