apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
#  namespace: clean
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: clearrworld@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - http01:
        ingress:
          class: nginx
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sid-com-tls
  namespace: clean
spec:
  secretName: sid-com-tls
  duration: 2160h # 90일
  renewBefore: 360h
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: server.si-d.site
  dnsNames:
  - server.si-d.site